FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD FibonacciService.jar /opt/FibonacciService/
EXPOSE 8080
WORKDIR /opt/FibonacciService/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "FibonacciService.jar"]
